### ISSUE TITLE
Please update the release note to version 14366

### ISSUE THREAD

**Issue by EdiWang** [ms-iot/content#922]
Recently Windows 10 IoT Core has been updated to 14366. But the release note document is not up to date. 

I notice the I2C ports on 14366 is not working, if there is some workaround please write into the document... It's really blocking me from doing IoT projects...

**Comment by mjmeans** [comment]
As stated on the forums, a new image will be up shortly and 14366 has been removed from the update process. 14366 requires a BSP change that is not able to be installed via update. So 14366 must be installed by re-flashing.

**Comment by IoTGirl** [comment]
Hi EdiWang,
This issue _only_ impacted Raspberry Pi due to the BSP issue mentioned above.  In future, the more information about the exact problem you are hitting with the exact sample you are using would be very helpful.  With the release of the full image with the new BSP we are considering this issue resolved so I am closing this issue.
Sincerest thanks for all of your feedback,
IoTGirl
